POST http://localhost:3003/api/comments
Content-Type: application/json

{
    "content": "Testikommentti 3",
    "blog": "6447e1207796cbd59ea48f06"
}

###
POST http://localhost:3003/api/comments
Content-Type: application/json

{
    "content": "Mitäköhän Dan ei tiedä vuonna 2023?",
    "blog": "6437f390d33f36157a339b5d"
}

###
POST http://localhost:3003/api/blogs/6447e1207796cbd59ea48f06/comments
Content-Type: application/json

{
    "content": "Testataan reititystä",
    "blog": "6447e1207796cbd59ea48f06"
}

###
DELETE http://localhost:3003/api/comments/6465160bf9ffd1e26156cbe5